development:
  adapter: postgresql
  database: dev
  pool: 50
  timeout: 5000
  username: oleg_gorbunov

test:
  adapter: postgresql
  database: test
  pool: 5
  timeout: 5000
  username: oleg_gorbunov

production:
  adapter: postgresql
  database: prod
  pool: 5
  timeout: 5000
  username: oleg_gorbunov
